repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
        exclude: ^migrations/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3
        exclude: ^migrations/
        additional_dependencies:
          [flake8-django, flake8-bugbear, flake8-bandit, pep8-naming]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        exclude: min\.js$
        types_or: [javascript, html, vue]
        exclude_types: [css]
