# Generated by Django 3.1.5 on 2021-02-09 04:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_azure_ad", "0002_UPDATE_SITE_NAME"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_token",
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_expiry",
            field=models.DateField(default=datetime.datetime(2100, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="email address"
            ),
        ),
    ]
