# Generated by Django 3.1.5 on 2021-02-09 04:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Member"),
                            (2, "Lead"),
                            (3, "Admin"),
                            (4, "Super Admin"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "name",
                    models.CharField(
                        error_messages={"required": "A team name is required"},
                        max_length=128,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "lead",
                    models.OneToOneField(
                        limit_choices_to={"user_type": 2},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="base.userprofile",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        limit_choices_to={"user_type": 1},
                        related_name="teams",
                        to="base.UserProfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"required": "A dept name is required"},
                        max_length=128,
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True, related_name="departments", to="base.Team"
                    ),
                ),
            ],
        ),
    ]
